# Generated by Django 4.2.5 on 2023-09-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('file', models.FileField(upload_to='files')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('certificate', models.FileField(upload_to='files')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('cv_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
                ('primary_image', models.ImageField(upload_to='')),
                ('secondary_image', models.ImageField(upload_to='')),
                ('about', models.TextField(max_length=1024)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.portfolio')),
            ],
        ),
    ]
