# Generated by Django 4.2.5 on 2023-09-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_education_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='description',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
