# Generated by Django 4.2.5 on 2023-09-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_professionalexperience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='profile',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
