# Generated by Django 4.2.5 on 2023-09-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='Skill',
        ),
    ]
